### ISSUE TITLE
数据集漏标等

### ISSUE THREAD

**Issue by NathanaelCat** [LiamLian0727/WaterMask#4]
您好，我注意到您发布的数据集存在一些漏标情况。
如果按照您的分类标准，数据集的图像存在很多漏标的情况，典型的包括reefs和sea-floor互相的错标和漏标，如reefs和sea-floor作为大目标存在于图像时，以及一些小目标的漏标情况，如远景中的潜水员、鱼类等，另外还有分类标准模糊，如reefs和sea-floor在多数图像中难以界定。
在使用通用分割模型预测时，正确预测出了ground truth中没有标注的目标。
请问这些情况应该如何处理？会有哪些影响？以及是否可以忽略？
期待与感谢您的回复。

**Comment by LiamLian0727** [comment]
There will inevitably be some errors in the dataset annotation, but our annotation team is trying their best to make the mask as good as they can. Also, we are preparing to upgrade the UIIS dataset to a larger and more accurate version, so please stay tuned to see what we are doing.
In order to deal with the problem that reefs and sea floors are difficult to define, our annotator groups corals with the same appearance into a coral reef mask, and uses this to gradually disassemble the huge coral group, if you find the incorrect annotations of categories such as reefs and sea-floors, you are welcome to report it to us.

**Comment by LiamLian0727** [comment]
Prediction using a generalized segmentation model (e.g., SAM) is likely to over-segment the image, and if you find a target that the model correctly predicted but not labeled in the dataset, you can manually add it to the GT’s json, and if you find a model that predicted it incorrectly, you can refer to CoralSCOP (CVPR' 24) to consider those parts of the generated redundant masks that do not overlap with the masks in GT as masks labeled with “background”.

**Comment by LiamLian0727** [comment]
And for targets that are too small in the dataset (e.g., plankton), we usually treat them as part of the ocean snow phenomenon and relegate them to the background.

**Comment by LiamLian0727** [comment]
Finally, we also present the existing largest underwater salient instance segmentation dataset [USIS10K](https://github.com/LiamLian0727/USIS10K), you can try it as well. Thank you very much for your issue, and please cite us if you feel our work makes sense!
```
@InProceedings{Lian_2023_ICCV,
    author    = {Lian, Shijie and Li, Hua and Cong, Runmin and Li, Suqi and Zhang, Wei and Kwong, Sam},
    title     = {WaterMask: Instance Segmentation for Underwater Imagery},
    booktitle = {Proceedings of the IEEE/CVF International Conference on Computer Vision (ICCV)},
    month     = {October},
    year      = {2023},
    pages     = {1305-1315}
}
@inproceedings{
  lian2024diving,
  title={Diving into Underwater: Segment Anything Model Guided Underwater Salient Instance Segmentation and A Large-scale Dataset},
  author={Shijie Lian and Ziyi Zhang and Hua Li and Wenjie Li and Laurence Tianruo Yang and Sam Kwong and Runmin Cong},
  booktitle={Forty-first International Conference on Machine Learning},
  year={2024},
  url={https://openreview.net/forum?id=snhurpZt63}
}
```

**Comment by LiamLian0727** [comment]
I hope my answer has solved your questions, if you have any other questions, please do not hesitate to contact me or send me a note via issue. Thanks again for your support in our work!
